odiseo_sylius_blog_plugin_shop_article_show:
    path: /article/{slug}
    methods: [GET]
    defaults:
        _controller: odiseo_blog.controller.article:showAction
        _sylius:
            template: "@OdiseoSyliusBlogPlugin/Shop/Article/show.html.twig"
            repository:
                method: findOneBySlugAndChannel
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - "expr:service('sylius.context.channel').getChannel().getCode()"

odiseo_sylius_blog_plugin_shop_article_index_by_category:
    path: /category/{slug}
    methods: [GET]
    defaults:
        _controller: odiseo_blog.controller.article:indexAction
        _sylius:
            template: "@OdiseoSyliusBlogPlugin/Shop/Article/index.html.twig"
            repository:
                method: findByCategoryAndChannel
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - "expr:service('sylius.context.channel').getChannel().getCode()"

odiseo_sylius_blog_plugin_shop_article_index:
    path: /
    methods: [GET]
    defaults:
        _controller: odiseo_blog.controller.article:indexAction
        _sylius:
            template: "@OdiseoSyliusBlogPlugin/Shop/Article/index.html.twig"
            repository:
                method: findByChannel
                arguments:
                    - "expr:service('sylius.context.channel').getChannel().getCode()"
